/** Declaration file generated by dts-gen */

export = git_url_parse;

declare function git_url_parse(url: any): any;

declare namespace git_url_parse {
    const prototype: {
    };

    function stringify(obj: any, type: any): any;

    namespace stringify {
        const prototype: {
        };
    }
}
