version: 2
executorType: machine
jobs:
  build:
    steps:
      - run: java -version

      - checkout

      - restore_cache:
          key: concord-{{ checksum "pom.xml" }}

      - run: ./mvnw -B dependency:go-offline > /dev/null

      - save_cache:
          paths:
            - ~/.m2
          key: concord-{{ checksum "pom.xml" }}

      - run: ./mvnw -B clean install -Pdocker

      # TODO rest of the tests
      - run: ./mvnw -B -f it/compat clean install -Pdocker -Pit
      - run: ./mvnw -B -f it/runtime-v1 clean install -Pdocker -Pit
      - run: ./mvnw -B -f it/runtime-v2 clean install -Pdocker -Pit
