flows:
  main:
  - script: javascript
    body: |
      execution.setVariable("name", "Concord");

  # call another flow
  - sayHello

  # call another flow and add/override its variables
  - call: sayHello
    in:
      name: "world"

  sayHello:
  - log: "Hello, ${name}"

configuration:
  entryPoint: main
