export const history = {
    FETCH_HISTORY_DATA_REQUEST: "FETCH_HISTORY_DATA_REQUEST",
    FETCH_HISTORY_DATA_RESULT: "FETCH_HISTORY_DATA_RESULT",

    KILL_PROC_REQUEST: "KILL_PROC_REQUEST",
    KILL_PROC_RESULT: "KILL_PROC_RESULT"
};

export const projectList = {
    FETCH_PROJECT_LIST_REQUEST: "FETCH_PROJECT_LIST_REQUEST",
    FETCH_PROJECT_LIST_RESULT: "FETCH_PROJECT_LIST_RESULT",

    DELETE_PROJECT_REQUEST: "DELETE_PROJECT_REQUEST",
    DELETE_PROJECT_RESULT: "DELETE_PROJECT_RESULT"
};

export const log = {
    FETCH_LOG_DATA_REQUEST: "FETCH_LOG_DATA_REQUEST",
    FETCH_LOG_DATA_RESULT: "FETCH_LOG_DATA_RESULT"
};

export default {history, projectList, log};