const history = {
    FETCH_HISTORY_DATA_REQUEST: "FETCH_HISTORY_DATA_REQUEST",
    FETCH_HISTORY_DATA_SUCCESS: "FETCH_HISTORY_DATA_SUCCESS",
    FETCH_HISTORY_DATA_FAILURE: "FETCH_HISTORY_DATA_FAULURE",

    KILL_PROC_REQUEST: "KILL_PROC_REQUEST",
    KILL_PROC_SUCCESS: "KILL_PROC_SUCCESS",
    KILL_PROC_FAILURE: "KILL_PROC_FAILURE"
};

const log = {
    FETCH_LOG_DATA_REQUEST: "FETCH_LOG_DATA_REQUEST",
    FETCH_LOG_DATA_SUCCESS: "FETCH_LOG_DATA_SUCCESS",
    FETCH_LOG_DATA_FAILURE: "FETCH_LOG_DATA_FAILURE"
};

const session = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE"
};

export default {history, log, session};