apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: concord-agent-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - configmaps
      - pods/exec
    verbs:
      - '*'

  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'

  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get

  - apiGroups:
      - concord.walmartlabs.com
    resources:
      - '*'
    verbs:
      - '*'
