configuration:
  runtime: "concord-v2"

flows:
  onChange:
  - name: "Filter to enabled repositories"
    expr: ${event.repositoryInfo.stream().filter(r -> r.enabled).toList()}
    out: repoIdsToRefresh
  - if: ${repoIdsToRefresh.size() > 0}
    then:
      - task: repositoryRefresh
        in:
          repositoryInfo: ${repoIdsToRefresh}

triggers:
  - concord:
      version: 2
      conditions:
        event: "repository.*"
      entryPoint: "onChange"

  - github:
      version: 2
      entryPoint: "onChange"
      conditions:
        type: "push"
        githubOrg: ".*"
        githubRepo: ".*"
        branch: ".*"
        repositoryInfo:
          # trigger only for registered enabled repos (i.e. added to Concord)
          - repository: ".*"
            enabled: true
