configuration:
  dependencies:
  - "mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:1.76.1"

flows:
  default:
  - task: ansible
    in:
      # arguments: [org name], inventory name, ansible host group name, query name, query params, [additional inventory variables]
      inventory: "${inventory.ansible('Default', 'myInventory', 'myHostsGroup', 'endpointsByZypperVersion', {'facter_zypper_version': '1.6.333'})}"
      # will produce a JSON structure like this:
      # {
      #   "myHostsGroup": {
      #     "hosts":["xx.xxx.xx.xxx"]
      #   },
      #   "_meta": {
      #     "hostvars":{
      #       "xx.xxx.xx.xxx":{
      #         "ansible_connection":"local"
      #       }
      #     }
      #   }
      # }

      playbook: playbook/hello.yml
      extraVars:
        greetings: "Hi there!"
