/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://oss.oracle.com/licenses/CDDL+GPL-1.1
 * or LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at LICENSE.txt.
 *
 * GPL Classpath Exception:
 * Oracle designates this particular file as subject to the "Classpath"
 * exception as provided by Oracle in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

/* Generated By:JavaCC: Do not edit this line. ELParserTreeConstants.java Version 5.0 */
package com.sun.el.parser;

/*-
 * *****
 * Concord
 * -----
 * Copyright (C) 2017 - 2025 Walmart Inc.
 * -----
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =====
 */

public interface ELParserTreeConstants
{
  public int JJTCOMPOSITEEXPRESSION = 0;
  public int JJTLITERALEXPRESSION = 1;
  public int JJTDEFERREDEXPRESSION = 2;
  public int JJTDYNAMICEXPRESSION = 3;
  public int JJTVOID = 4;
  public int JJTSEMICOLON = 5;
  public int JJTASSIGN = 6;
  public int JJTLAMBDAEXPRESSION = 7;
  public int JJTLAMBDAPARAMETERS = 8;
  public int JJTCHOICE = 9;
  public int JJTOR = 10;
  public int JJTAND = 11;
  public int JJTEQUAL = 12;
  public int JJTNOTEQUAL = 13;
  public int JJTLESSTHAN = 14;
  public int JJTGREATERTHAN = 15;
  public int JJTLESSTHANEQUAL = 16;
  public int JJTGREATERTHANEQUAL = 17;
  public int JJTCONCAT = 18;
  public int JJTPLUS = 19;
  public int JJTMINUS = 20;
  public int JJTMULT = 21;
  public int JJTDIV = 22;
  public int JJTMOD = 23;
  public int JJTNEGATIVE = 24;
  public int JJTNOT = 25;
  public int JJTEMPTY = 26;
  public int JJTVALUE = 27;
  public int JJTDOTSUFFIX = 28;
  public int JJTBRACKETSUFFIX = 29;
  public int JJTMETHODARGUMENTS = 30;
  public int JJTMAPDATA = 31;
  public int JJTMAPENTRY = 32;
  public int JJTLISTDATA = 33;
  public int JJTIDENTIFIER = 34;
  public int JJTFUNCTION = 35;
  public int JJTTRUE = 36;
  public int JJTFALSE = 37;
  public int JJTFLOATINGPOINT = 38;
  public int JJTINTEGER = 39;
  public int JJTSTRING = 40;
  public int JJTNULL = 41;


  public String[] jjtNodeName = {
    "CompositeExpression",
    "LiteralExpression",
    "DeferredExpression",
    "DynamicExpression",
    "void",
    "SemiColon",
    "Assign",
    "LambdaExpression",
    "LambdaParameters",
    "Choice",
    "Or",
    "And",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "LessThanEqual",
    "GreaterThanEqual",
    "Concat",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "Mod",
    "Negative",
    "Not",
    "Empty",
    "Value",
    "DotSuffix",
    "BracketSuffix",
    "MethodArguments",
    "MapData",
    "MapEntry",
    "ListData",
    "Identifier",
    "Function",
    "True",
    "False",
    "FloatingPoint",
    "Integer",
    "String",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=295bae338407e43a1d349f1ce802614a (do not edit this line) */
